language: php
php:
- 7.1
before_install:
# this is an example, add your own keys hete
# - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv
  # -in scripts/travis_deploy.enc -out  /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan key:generate
- "./vendor/bin/phpunit --coverage-clover=coverage.xml"
after_success:
- bash <(curl -s https://codecov.io/bash)
- rm .env
- echo "Unicorn Time"
deploy:
  - provider: script
    script: "./scripts/travis.sh"
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: "./scripts/travis.sh"
    skip_cleanup: true
    on:
      branch: master
